sudo: required

language: php

php:
  - '7.2'

services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE_SERVICE:latest ./image-service
  - docker build -t $DOCKER_VIEW_SERVICE:latest ./viewer-service
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE_SERVICE:latest
  - docker-compose up -d

before_script:
  - php -l ./image-service/image.php
  - sh test.sh
  - docker ps | grep -q $DOCKER_IMAGE_SERVICE
  - docker ps | grep -q $DOCKER_VIEW_SERVICE

script:
  - sed -i -e "s/localhost/$DOMAIN/g" viewer-service/index.html

after_success:
  - curl -k -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - ./sloppy change -v docker_image:"$DOCKER_IMAGE_SERVICE:latest" -v domain:"$DOMAIN" $SLOPPY_FILE

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: viewer-service
