services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE:latest ./image-service
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:latest
  - docker run -d $DOCKER_IMAGE:latest

script:
  - docker ps | grep -q $DOCKER_IMAGE
  - sed -i -e "s/localhost/$DOMAIN/g" viewer-service/index.html

after_success:
  - curl -k -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - ./sloppy change -v docker_image:"$DOCKER_IMAGE:latest" -v domain:"$DOMAIN" $SLOPPY_FILE

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: viewer-service
